### ISSUE TITLE
what version of node is required?

### ISSUE THREAD

**Issue by yeahsmaggy** [colophonemes/drupal-to-markdown#4]
I can't tell what versino of node is required and I'm getting a lot of errors on npm install

e.g.

npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function
npm ERR! asyncWrite is not a function

**Comment by staropram** [comment]
I got it to work with version 4.0.0 using nvm to install that version

I was also able to get it to convert drupal 6 by changing some db table names and field names
